export const INCREMENT_HAND = 'INCREMENT_HAND';
export const HAND_EXCEEDED = 'HAND_EXCEEDED';
export const SUBMIT_QUESTION = 'SUBMIT_QUESTION';
export const QUESTION_ERROR = 'QUESTION_ERROR';
export const SUBMIT_WORD_TO_GUESS = 'SUBMIT_WORD_TO_GUESS';
